/* User Reducer Actions */
export const SET_USER = "SET_USER";
export const UNSET_USER = "REMOVE_USER";
export const FETCH_USER = "FETCH_USER";


/* FOURM TOPIC ACTIONS */
export const ADD_TOPIC = "ADD_TOPIC";
export const REMOVE_TOPIC = "REMOVE_TOPIC";
export const SET_TOPICS = "SET_TOPICS";
export const FILTER_TOPICS = "FILTER_TOPICS";

/* FOURM CATEGORY ACTIONS */
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_CATEGORYS = "SET_CATEGORYS";

/* FOURM THREAD ACTIONS */
export const ADD_THREADS = "ADD_THREADS";
export const CREATE_THREAD = "CREATE_THREAD";
export const FETCH_THREADS = "FETCH_THREADS";
export const SET_THREAD_OWNER = "SET_THREAD_OWNER";

/* ADMIN ACTIONS */
export const ADMIN_DELETE_THREAD = "ADMIN_DELETE_THREAD";
export const ADMIN_PIN_THREAD = "ADMIN_PIN_THREAD";
export const ADMIN_LOCK_THREAD = "ADMIN_LOCK_THREAD";